// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20181202120445_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.ReadLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Details");

                    b.HasKey("Id");

                    b.ToTable("ReadLog");
                });

            modelBuilder.Entity("Data.TemperatureMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(9,4)");

                    b.Property<int?>("WatherStationId");

                    b.HasKey("Id");

                    b.HasIndex("WatherStationId");

                    b.ToTable("TemperatureMeasurement");
                });

            modelBuilder.Entity("Data.WatherStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ExternalKey");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("WatherStation");
                });

            modelBuilder.Entity("Data.TemperatureMeasurement", b =>
                {
                    b.HasOne("Data.WatherStation", "WatherStation")
                        .WithMany()
                        .HasForeignKey("WatherStationId");
                });
#pragma warning restore 612, 618
        }
    }
}
